title: Hari Krishna Vydana
description: "A brief profile of Hari Krishna Vydana."
url: "https://harikrishna-vydana.github.io"
theme: minima

social:
  - icon: fa-linkedin
    icon_pack: fab
    link: https://www.linkedin.com/in/hari-krishna-vydana-0b014b87
  - icon: fa-github
    icon_pack: fab
    link: https://github.com/HariKrishna-Vydana

# Enable pagination (if you add blog posts)
paginate: 5

# Navigation menu
navigation:
  main:
    - title: "Home"
      url: /
    - title: "About"
      url: /about/
    - title: "CV"
      url: /cv/
